server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:crm_ips}
    username: ${DB_USER:crm_user}
    password: ${DB_PASS:crm_pass_2026}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: America/Bogota

app:
  security:
    jwt:
      secret: ${JWT_SECRET:4DAE1UGpEUWcrWHbbIyR01y2KRCBmei+eDV3p5V87nJNBF3l9woyZM+7aTGOOKUnYXlvqZAZYO5AN7qNkD8Kug==}
      expiration-minutes: ${JWT_EXPIRATION_MINUTES:480}

  init:
    admin-email:    ${ADMIN_EMAIL:admin@crm.local}
    admin-password: ${ADMIN_PASSWORD:Admin2026*}
    admin-name:     ${ADMIN_NAME:Administrador}
